### PR TITLE
Add privacy manifest 

### PR DESCRIPTION
**Pull request by KantaSwift**
## Summary
To comply with Apple's new privacy policies every third-party SDK should include a Privacy manifest in case if they access APIs which potentially can be used for fingerprinting.
So, I believe it falls under the following content, I add the PrivacyInfo.xcprivacy

- [C56D.1 ](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api)

### CODE REVIEW

**Comment by Ryu0118** [comment]
これってSources/UserDefaultsEditorに置く話になったんじゃなかったっけ

**Comment by Ryu0118** [comment]
@KantaSwift これってSources/UserDefaultsEditorに置く話になったんじゃなかったっけ

**Comment by KantaSwift** [comment]
@Ryu0118 
Sources/UserDefaultsEditorの中に入れましたー！

**Review by Ryu0118 — APPROVED** [review]
Thanks!

**Pull request merged**
